import api, { unwrap } from './api';

export const adminService = {
  dashboard: () => unwrap(api.get('/admin/dashboard')),
  users: () => unwrap(api.get('/admin/users')),
  updateUser: (id, payload) => unwrap(api.put(`/admin/users/${id}`, payload)),
  products: () => unwrap(api.get('/admin/products')),
  createProduct: (payload) => unwrap(api.post('/admin/products', payload)),
  updateProduct: (id, payload) => unwrap(api.put(`/admin/products/${id}`, payload)),
  deleteProduct: (id) => unwrap(api.delete(`/admin/products/${id}`)),
  orders: () => unwrap(api.get('/admin/orders')),
  updateOrder: (id, payload) => unwrap(api.put(`/admin/orders/${id}`, payload)),
  catalogues: () => unwrap(api.get('/admin/catalogues')),
  createCatalogue: (payload) => unwrap(api.post('/admin/catalogues', payload)),
  updateCatalogue: (id, payload) => unwrap(api.put(`/admin/catalogues/${id}`, payload)),
  deleteCatalogue: (id) => unwrap(api.delete(`/admin/catalogues/${id}`)),
  promotions: () => unwrap(api.get('/admin/promotions')),
  createBanner: (payload) => unwrap(api.post('/admin/promotions/banners', payload)),
  updateBanner: (id, payload) => unwrap(api.put(`/admin/promotions/banners/${id}`, payload)),
  deleteBanner: (id) => unwrap(api.delete(`/admin/promotions/banners/${id}`)),
  updateBannerOrder: (order) => unwrap(api.put('/admin/promotions/banners-order', { order })),
  createPopupAd: (payload) => unwrap(api.post('/admin/promotions/popup-ads', payload)),
  updatePopupAd: (id, payload) => unwrap(api.put(`/admin/promotions/popup-ads/${id}`, payload)),
  deletePopupAd: (id) => unwrap(api.delete(`/admin/promotions/popup-ads/${id}`)),
  createEvent: (payload) => unwrap(api.post('/admin/events', payload)),
  updateEvent: (id, payload) => unwrap(api.put(`/admin/events/${id}`, payload)),
  deleteEvent: (id) => unwrap(api.delete(`/admin/events/${id}`)),
  config: () => unwrap(api.get('/admin/config')),
  updateConfig: (payload) => unwrap(api.put('/admin/config', payload)),
  testimonials: () => unwrap(api.get('/admin/testimonials')),
  createTestimonial: (payload) => unwrap(api.post('/admin/testimonials', payload)),
  updateTestimonial: (id, payload) => unwrap(api.put(`/admin/testimonials/${id}`, payload)),
  deleteTestimonial: (id) => unwrap(api.delete(`/admin/testimonials/${id}`)),
  roles: () => unwrap(api.get('/admin/roles')),
  reports: (type) => unwrap(api.get(`/admin/reports/${type}`)),
  sync: () => unwrap(api.get('/admin/sync')),
  triggerSync: () => unwrap(api.post('/admin/sync')),
};
